[package]

name = "errno"
version = "0.2.1"
authors = ["Chris Wong <lambda.fairy@gmail.com>"]

license = "MIT/Apache-2.0"
documentation = "https://docs.rs/errno"
repository = "https://github.com/lfairy/rust-errno"
description = "Cross-platform interface to the `errno` variable."
categories = ["os"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[badges]
travis-ci = { repository = "lfairy/rust-errno" }
